[project]
name = "sandbox"
version = "0.0.1"
dependencies = [
  "azureml-core==1.58.0",
  "pandas==2.2.3",
  "pytest==8.3.3",
  "python-dotenv==1.0.1",
  "safetensors==0.4.5",
  "setuptools==75.6.0",
  "torch==2.5.1",
]
requires-python = ">=3.12"
authors = [
  {name = "Davy Toch"},
]